version: "2.4"
networks:
  # declis-net:
  #   external:
  #     name: declis-net
  traefik_web:
    external:
      name: traefik_web
services:
  declisweb:
    user: "1016:33"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: declis
    ports:
      - 5011:5011
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.port=5011"
      - "traefik.http.routers.declisweb.rule=Host(`declis.devserver.pharmb.io`)"
      - "traefik.http.routers.declisweb.entrypoints=websecure"
      - "traefik.http.routers.declisweb.tls.certresolver=myresolver"
    networks:
      # - declis-net
      - traefik_web
    volumes:
      - ../remote/static:/home/declis/app/static:ro
      - ../remote/data:/home/declis/data:rw
      # - ./app:/home/declis/app
      - ./:/home/declis

# docker run -it --rm -i -v ${HOME}/declis/remote/static:/static \
# -w /static -u ${UID}:33 mcs07/rdkit:latest /bin/bash
# docker exec -it `docker container ls | awk '/declis/ {print $1}'` /bin/bash